# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: MiniMax M3
    provider: ollama
    model: minimax-m3:cloud
    roles:
      - chat
      - edit
      - apply
      - autocomplete